### ISSUE TITLE
绑定用户失败

### ISSUE THREAD

**Issue by Mashiroyes** [yaowan233/nonebot-plugin-osubot#15]
只要使用bind命令，就会提示下面的错误，请问如何解决

![image](https://user-images.githubusercontent.com/59597481/212526437-be970e67-88fc-4fcb-aa21-eb1a062d8bf5.png)

**Comment by Mashiroyes** [comment]
上面的提示应该是数据库中没有对应的用户信息，但是绑定用户不应该是通过osu应用的客户端到官网查询到用户信息然后绑定吗，怎么会直接从数据库中查询

**Comment by yaowan233** [comment]
请检查是否有其他插件也使用了tortoise数据库，如果有会造成插件冲突

**Comment by Mashiroyes** [comment]
> 请检查是否有其他插件也使用了tortoise数据库，如果有会造成插件冲突，已知会冲突的插件有learning chat与hoshinobot

好的，多谢，我去检查下
