### ISSUE TITLE
[协议支持] 支持新协议适配器

### ISSUE THREAD

**Issue by yaowan233** [yaowan233/nonebot-plugin-osubot#38]
由于https://github.com/Mrs4s/go-cqhttp/issues/2471, 接下来会更新Red适配器的内容或者是QQ 的官方接口，同时将重构matcher部分，不在一个__init__.py下面塞那么多代码了

**Comment by mas-alone** [comment]
辛苦大佬们的无私奉献

**Comment by Dreamail** [comment]
建议迁移到nonebot_plugin_saa插件
该插件可以用于转接多种adapter

**Comment by yaowan233** [comment]
> 建议迁移到nonebot_plugin_saa插件 该插件可以用于转接多种adapter

主要我这个插件有的功能需要发送语音以及直接发送文件，有的功能还要群内成员信息，saa可能不太可行
