### ISSUE TITLE
响应太慢了，要等好几分钟才能查到记录

### ISSUE THREAD

**Issue by NanakoOfficial** [yaowan233/nonebot-plugin-osubot#4]
有没有啥解决方法呀

**Comment by yaowan233** [comment]
如果是查询单图成绩的话是要从https://osu.sayobot.cn 上下载地图
如果是这个比较慢可能是服务器在国外 地图下的比较慢
如果是查询info的话是直接用的官网的api的
这个慢的话可能是连接osu官网比较慢

**Comment by NanakoOfficial** [comment]
大佬，SEND_MSG_API_ERROR是咋回事呀

nonebot.adapters.onebot.v11.exception.ActionFailed: <ActionFailed data=None, echo={'seq': 16}, msg=SEND_MSG_API_ERROR, retcode=100, status=failed, wording=请参考 go-cqhttp 端输出>

gocqhttp端显示 ：[ERROR]: Protocol -> sendPacket msg error: 120

**Comment by yaowan233** [comment]
> 大佬，SEND_MSG_API_ERROR是咋回事呀
> 
> nonebot.adapters.onebot.v11.exception.ActionFailed: <ActionFailed data=None, echo={'seq': 16}, msg=SEND_MSG_API_ERROR, retcode=100, status=failed, wording=请参考 go-cqhttp 端输出>
> 
> gocqhttp端显示 ：[ERROR]: Protocol -> sendPacket msg error: 120

这个应该是gocqhttp的问题 可以试试重启gocq就行了

**Comment by NanakoOfficial** [comment]
> > 大佬，SEND_MSG_API_ERROR是咋回事呀
> > 
> > nonebot.adapters.onebot.v11.exception.ActionFailed: <ActionFailed data=None, echo={'seq': 16}, msg=SEND_MSG_API_ERROR, retcode=100, status=failed, wording=请参考 go-cqhttp 端输出>
> > 
> > gocqhttp端显示 ：[ERROR]: Protocol -> sendPacket msg error: 120
> 
> 这个应该是gocqhttp的问题 可以试试重启gocq就行了

好的，感谢大佬
