### ISSUE TITLE
提取背景不能用怎么回事

### ISSUE THREAD

**Issue by laobai8888** [yaowan233/nonebot-plugin-osubot#5]
转换CQ码 ({"type": "image", "data": {"file": "file:///data\\osu\\map\\1279298\\korone daisuki sukisukisuki chu chuchu chu.jpg", "type": null, "cache": "true", "proxy": "true", "timeout": null}}) 到MiraiGo Element时出现错误: file not found 将忽略本段CQ码.

**Comment by laobai8888** [comment]
查询图组也不能用...显示 Error: <class 'aiohttp.client_exceptions.ClientConnectorCertificateError'>
下载地图只艾特我

**Comment by yaowan233** [comment]
> 转换CQ码 ({"type": "image", "data": {"file": "file:///data\osu\map\1279298\korone daisuki sukisukisuki chu chuchu chu.jpg", "type": null, "cache": "true", "proxy": "true", "timeout": null}}) 到MiraiGo Element时出现错误: file not found 将忽略本段CQ码.

已修复

**Comment by yaowan233** [comment]
> 查询图组也不能用...显示 Error: <class 'aiohttp.client_exceptions.ClientConnectorCertificateError'> 下载地图只艾特我

现取消ssl验证来修复此问题
