### ISSUE TITLE
mania转谱成绩查询 键数不正确

### ISSUE THREAD

**Issue by Exsper** [yaowan233/nonebot-plugin-osubot#52]
可以参考lazer源码：

https://github.com/ppy/osu/blob/master/osu.Game.Rulesets.Mania/Beatmaps/ManiaBeatmapConverter.cs#L58

**Comment by yaowan233** [comment]
能给一个例子吗？

**Comment by Exsper** [comment]
> 能给一个键数不正确的成绩的例子吗？

![Cache_-7d7255062da7e97e.png](https://github.com/yaowan233/nonebot-plugin-osubot/assets/25431144/1d8e39eb-d663-4c56-a7ba-b6362d04a67f)

键位数量应为4

**Comment by mas-alone** [comment]
可能是一个可行的方案？OD+1后如果还没有匹配到，则CS+1?
```
    # 计算转谱键数
    temp_accuracy = mapinfo.accuracy
    for _ in range(2):
        convert = (mapinfo.count_sliders + mapinfo.count_spinners) / (mapinfo.count_circles + mapinfo.count_sliders + mapinfo.count_spinners)
        convert_od = round(temp_accuracy)
        if convert < 0.20:
            mapinfo.cs = 7.0
            break
        elif convert < 0.30 or round(mapinfo.cs) >= 5:
            if convert_od > 5:
                mapinfo.cs = 7.0
            else:
                mapinfo.cs = 6.0
            break
        elif convert > 0.60:
            if convert_od > 4:
                mapinfo.cs = 5.0
            else:
                mapinfo.cs = 4.0
            break
        else:
            temp_accuracy += 1
    else:
        mapinfo.cs = 4.0
```

**Comment by Exsper** [comment]
> 可能是一个可行的方案？OD+1后如果还没有匹配到，则CS=4?
> ```
>     # 计算转谱键数
>     if score_info.mode == 'mania' and mapinfo.mode == 'osu':
>         temp_accuracy = mapinfo.accuracy
>         for _ in range(2):
>             convert = (mapinfo.count_sliders + mapinfo.count_spinners) / (mapinfo.count_circles + mapinfo.count_sliders + mapinfo.count_spinners)
>             convert_od = round(temp_accuracy)
>             if convert < 0.20:
>                 mapinfo.cs = 7.0
>                 break
>             elif convert < 0.30 or round(mapinfo.cs) >= 5:
>                 if convert_od > 5:
>                     mapinfo.cs = 7.0
>                 else:
>                     mapinfo.cs = 6.0
>                 break
>             elif convert > 0.60:
>                 if convert_od > 4:
>                     mapinfo.cs = 5.0
>                 else:
>                     mapinfo.cs = 4.0
>                 break
>             else:
>                 temp_accuracy += 1
>         else:
>             mapinfo.cs = 4.0
> ```
> ![4adf4256b6f02392f54087fb4c629a52](https://github.com/yaowan233/nonebot-plugin-osubot/assets/52590027/a270b32c-60eb-4336-a236-afc514329218)
> 

ppy写的代码是，如果匹配不到，最后用OD+1，小于4取4，大于7取7

**Comment by mas-alone** [comment]
> > 可能是一个可行的方案？OD+1后如果还没有匹配到，则CS=4?
> > ```
> >     # 计算转谱键数
> >     if score_info.mode == 'mania' and mapinfo.mode == 'osu':
> >         temp_accuracy = mapinfo.accuracy
> >         for _ in range(2):
> >             convert = (mapinfo.count_sliders + mapinfo.count_spinners) / (mapinfo.count_circles + mapinfo.count_sliders + mapinfo.count_spinners)
> >             convert_od = round(temp_accuracy)
> >             if convert < 0.20:
> >                 mapinfo.cs = 7.0
> >                 break
> >             elif convert < 0.30 or round(mapinfo.cs) >= 5:
> >                 if convert_od > 5:
> >                     mapinfo.cs = 7.0
> >                 else:
> >                     mapinfo.cs = 6.0
> >                 break
> >             elif convert > 0.60:
> >                 if convert_od > 4:
> >                     mapinfo.cs = 5.0
> >                 else:
> >                     mapinfo.cs = 4.0
> >                 break
> >             else:
> >                 temp_accuracy += 1
> >         else:
> >             mapinfo.cs = 4.0
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ![4adf4256b6f02392f54087fb4c629a52](https://private-user-images.githubusercontent.com/52590027/317120287-a270b32c-60eb-4336-a236-afc514329218.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE1MTM2MDQsIm5iZiI6MTcxMTUxMzMwNCwicGF0aCI6Ii81MjU5MDAyNy8zMTcxMjAyODctYTI3MGIzMmMtNjBlYi00MzM2LWEyMzYtYWZjNTE0MzI5MjE4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI3VDA0MjE0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQzYjkyYWZjYjM4ZGI5ZWFlYjE4ZjFmN2NiODc2Nzg4MWJiZmI5YWY0ZTUwYjdkZWRmZDFhNDg5NTk0MjZiMzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.FI0-6baqsJP1wlPJcrUvMmHj_086yLU9s-W15cu9UR8)
> 
> ppy写的代码是，如果匹配不到，最后用OD+1，小于4取4，大于7取7，这个是无条件的，不存在其他情况 ![Screenshot_20240327_112325.jpg](https://private-user-images.githubusercontent.com/25431144/317122831-f3d90e4b-4ab6-4d26-84eb-1a44795495d3.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE1MTM2MDQsIm5iZiI6MTcxMTUxMzMwNCwicGF0aCI6Ii8yNTQzMTE0NC8zMTcxMjI4MzEtZjNkOTBlNGItNGFiNi00ZDI2LTg0ZWItMWE0NDc5NTQ5NWQzLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI3VDA0MjE0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMxMjMyNTFmMWIzOGE1MDIzYWMyMDBlYjQwYmM5NTE4OTFmMGIyMDcwNjJmYWNkOGU1YzUzNjBkMTI4YzFlYmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.FQC_bs1Tox0s74EDY4gPZh7MUXtYBgK-Zsr5xtTVr2E)

按照peppy那边，那应该是这样
```
    # 计算转谱键数
    if score_info.mode == 'mania' and mapinfo.mode == 'osu':
        temp_accuracy = mapinfo.accuracy
        for _ in range(2):
            convert = (mapinfo.count_sliders + mapinfo.count_spinners) / (mapinfo.count_circles + mapinfo.count_sliders + mapinfo.count_spinners)
            convert_od = round(temp_accuracy)
            if convert < 0.20 or (convert < 0.30 or round(mapinfo.cs) >= 5) and convert_od > 5:
                mapinfo.cs = 7.0
                break
            elif (convert < 0.30 or round(mapinfo.cs) >= 5) and convert_od <= 5:
                mapinfo.cs = 6.0
                break
            elif convert > 0.60 and convert_od > 4:
                mapinfo.cs = 5.0
                break
            elif convert > 0.60 and convert_od <= 4:
                mapinfo.cs = 4.0
                break
            else:
                temp_accuracy += 1
                mapinfo.cs = max(4.0, min(temp_accuracy, 7.0))
```

**Comment by yaowan233** [comment]
fix in https://github.com/yaowan233/nonebot-plugin-osubot/commit/0c937ed30b4642e0ba44f0811657c2c93e53cba6
