### ISSUE TITLE
似乎名字不支持空格

### ISSUE THREAD

**Issue by mas-alone** [yaowan233/nonebot-plugin-osubot#7]
例如:
`!pr P a P a P a`会显示查无此人。

另外一个问题是mania的谱面有些谱会错误的显示pp，好像是failed或者开启dt后就会。
![QQ图片20220905233310](https://user-images.githubusercontent.com/52590027/188485141-a6af3179-d86c-4d78-ac4d-ad885126bbdb.png)
![QQ图片20220905235358](https://user-images.githubusercontent.com/52590027/188485175-47d51b4b-b5d8-45bf-bdf0-a30639067a2e.png)

**Comment by yaowan233** [comment]
已修复名字不能有空格的问题
对于pp显示错误暂时无法解决 因为现使用的是由 https://github.com/Yuri-YuzuChaN/osuv2 提供的pp计算api 你可以向他反馈 如果我有空的话 会提供本地计算pp的方案

**Comment by mas-alone** [comment]
> 已修复名字不能有空格的问题 对于pp显示错误暂时无法解决 因为现使用的是由 https://github.com/Yuri-YuzuChaN/osuv2 提供的pp计算api 你可以向他反馈 如果我有空的话 会提供本地计算pp的方案

好，感谢<3
